services:
  superset:
    build:
      context: .
      dockerfile: docker/superset/Dockerfile
    container_name: netflix_bi_superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY:-change-this-local-dev-secret}
      SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME:-admin}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD:-admin}
      SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME:-Netflix}
      SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME:-BI}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL:-admin@example.com}
    volumes:
      - superset_home:/app/superset_home

volumes:
  superset_home:
